=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.0.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.56
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CheckoutApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CheckoutApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CheckoutApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutApi' do
    it 'should create an instance of CheckoutApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CheckoutApi)
    end
  end

  # unit tests for create_checkout
  # Create Checkout
  # Create checkout&lt;br&gt;&lt;br&gt;&lt;strong&gt;Since 2024.01&lt;/strong&gt;
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse201]
  describe 'create_checkout test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
