=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.1.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for Billabear::ReceiptApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReceiptApi' do
  before do
    # run before each test
    @instance = Billabear::ReceiptApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReceiptApi' do
    it 'should create an instance of ReceiptApi' do
      expect(@instance).to be_instance_of(Billabear::ReceiptApi)
    end
  end

  # unit tests for download_receipt
  # Download Receipt
  # Returns the pdf blob for the Receipt
  # @param receipt The id of the receipt
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_receipt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
