=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.1.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'

# Unit tests for Billabear::SubscriptionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubscriptionsApi' do
  before do
    # run before each test
    @instance = Billabear::SubscriptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionsApi' do
    it 'should create an instance of SubscriptionsApi' do
      expect(@instance).to be_instance_of(Billabear::SubscriptionsApi)
    end
  end

  # unit tests for add_seats_subscriptions
  # Add Seats
  # Adds seats to a per seat subscription&lt;br&gt;&lt;br&gt;&lt;strong&gt;Since 1.1.4&lt;/strong&gt;
  # @param body 
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20013]
  describe 'add_seats_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancel_subscription
  # Cancel Subscription
  # Info for a specific subscription
  # @param body 
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_subscription test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for change_subscription_price
  # Change Price
  # Changes the price being used for a price. Useful for changing pricing schedule or just price.
  # @param body 
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20013]
  describe 'change_subscription_price test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_subscription
  # Create Subscription
  # Create subscription for a customer
  # @param body 
  # @param customer_id The id of the customer to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Subscription]
  describe 'create_subscription test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_change_subscription_plan
  # Change Subscription Plan
  # Change the subscription plan for a customer
  # @param body 
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Subscription]
  describe 'customer_change_subscription_plan test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for extend_trial
  # Extend Trial Subscription
  # Extend a trial subscription so it&#x27;s converted from a trial to a normal subscription.
  # @param body 
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Subscription]
  describe 'extend_trial test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_active_for_customer
  # List Customer Active Subscriptions
  # List all Active customer subscriptions
  # @param customer_id The id of the customer to retrieve
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2008]
  describe 'get_active_for_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_for_customer
  # List Customer Subscriptions
  # List all customer subscriptions&lt;br&gt;&lt;br&gt;&lt;strong&gt;Since 1.1&lt;/strong&gt;
  # @param customer_id The id of the customer to retrieve
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2008]
  describe 'get_for_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_subscription_plans
  # List Subscription Plans
  # List all subscriptions plans
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit How many items to return at one time (max 100)
  # @option opts [String] :last_key The key to be used in pagination to say what the last key of the previous page was
  # @return [InlineResponse20012]
  describe 'list_subscription_plans test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_subscriptions
  # List
  # List all subscriptions
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit How many items to return at one time (max 100)
  # @option opts [String] :last_key The key to be used in pagination to say what the last key of the previous page was
  # @return [InlineResponse2008]
  describe 'list_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_seats_subscriptions
  # Remove Seats
  # Remove seats to a per seat subscription&lt;br&gt;&lt;br&gt;&lt;strong&gt;Since 1.1.4&lt;/strong&gt;
  # @param body 
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse20013]
  describe 'remove_seats_subscriptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_subscription_by_id
  # Detail
  # Info for a specific subscription
  # @param subscription_id The id of the subscription to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Subscription]
  describe 'show_subscription_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for start_trial
  # Start Trial Subscription For Customer
  # Start subscription for a customer
  # @param body 
  # @param customer_id The id of the customer to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Subscription]
  describe 'start_trial test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
