=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.0.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.56
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse20012
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse20012' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse20012.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse20012' do
    it 'should create an instance of InlineResponse20012' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse20012)
    end
  end
  describe 'test attribute "paid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "failure_reason"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["expired_card", "invalid_details", "fraud", "authentication_required", "invalid_card", "general_decline", "contact_provider", "lack_of_funds"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.failure_reason = value }.not_to raise_error
      # end
    end
  end

end
