=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.1.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Billabear::SubscriptionIdCancelBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubscriptionIdCancelBody' do
  before do
    # run before each test
    @instance = Billabear::SubscriptionIdCancelBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionIdCancelBody' do
    it 'should create an instance of SubscriptionIdCancelBody' do
      expect(@instance).to be_instance_of(Billabear::SubscriptionIdCancelBody)
    end
  end
  describe 'test attribute "_when"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["end-of-run", "instantly", "specific-date"])
      # validator.allowable_values.each do |value|
      #   expect { @instance._when = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "refund_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "full", "prorate"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.refund_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "comment"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
