=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.1.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.66
=end

# Common files
require 'billabear/api_client'
require 'billabear/api_error'
require 'billabear/version'
require 'billabear/configuration'

# Models
require 'billabear/models/address'
require 'billabear/models/billing_admin'
require 'billabear/models/checkout_body'
require 'billabear/models/checkout_items'
require 'billabear/models/checkout_subscriptions'
require 'billabear/models/cost'
require 'billabear/models/customer'
require 'billabear/models/customer_id_uasgelimit_body'
require 'billabear/models/error'
require 'billabear/models/event'
require 'billabear/models/feature'
require 'billabear/models/frontend_token'
require 'billabear/models/inline_response_200'
require 'billabear/models/inline_response_200_1'
require 'billabear/models/inline_response_200_10'
require 'billabear/models/inline_response_200_11'
require 'billabear/models/inline_response_200_12'
require 'billabear/models/inline_response_200_13'
require 'billabear/models/inline_response_200_14'
require 'billabear/models/inline_response_200_2'
require 'billabear/models/inline_response_200_3'
require 'billabear/models/inline_response_200_4'
require 'billabear/models/inline_response_200_5'
require 'billabear/models/inline_response_200_6'
require 'billabear/models/inline_response_200_7'
require 'billabear/models/inline_response_200_8'
require 'billabear/models/inline_response_200_9'
require 'billabear/models/inline_response_200_9_data'
require 'billabear/models/inline_response_200_9_receipts'
require 'billabear/models/inline_response_201'
require 'billabear/models/inline_response_201_lines'
require 'billabear/models/inline_response_400'
require 'billabear/models/invoice'
require 'billabear/models/invoice_lines'
require 'billabear/models/issue_refund_payment'
require 'billabear/models/limit'
require 'billabear/models/metric'
require 'billabear/models/metric_cost'
require 'billabear/models/metric_filter'
require 'billabear/models/payment_details'
require 'billabear/models/price'
require 'billabear/models/product'
require 'billabear/models/product_tax_type'
require 'billabear/models/refund'
require 'billabear/models/seats_add_body'
require 'billabear/models/seats_remove_body'
require 'billabear/models/subscription'
require 'billabear/models/subscription_id_cancel_body'
require 'billabear/models/subscription_id_extend_body'
require 'billabear/models/subscription_id_plan_body'
require 'billabear/models/subscription_id_price_body'
require 'billabear/models/subscription_plan'
require 'billabear/models/subscription_start_body'
require 'billabear/models/subscription_trial_body'
require 'billabear/models/usage_limit'
require 'billabear/models/voucher_code'

# APIs
require 'billabear/api/checkout_api'
require 'billabear/api/customers_api'
require 'billabear/api/invoices_api'
require 'billabear/api/payment_details_api'
require 'billabear/api/payments_api'
require 'billabear/api/prices_api'
require 'billabear/api/products_api'
require 'billabear/api/receipt_api'
require 'billabear/api/refunds_api'
require 'billabear/api/subscriptions_api'
require 'billabear/api/usage_api'

module Billabear
  class << self
    # Customize default settings for the SDK using block.
    #   Billabear.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
