=begin
#BillaBear

#The REST API provided by BillaBear

OpenAPI spec version: 1.0.0
Contact: support@billabear.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.56
=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/address'
require 'swagger_client/models/billing_admin'
require 'swagger_client/models/checkout_body'
require 'swagger_client/models/checkout_items'
require 'swagger_client/models/checkout_subscriptions'
require 'swagger_client/models/customer'
require 'swagger_client/models/error'
require 'swagger_client/models/feature'
require 'swagger_client/models/frontend_token'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_10'
require 'swagger_client/models/inline_response_200_11'
require 'swagger_client/models/inline_response_200_12'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_200_7'
require 'swagger_client/models/inline_response_200_7_data'
require 'swagger_client/models/inline_response_200_7_receipts'
require 'swagger_client/models/inline_response_200_8'
require 'swagger_client/models/inline_response_200_9'
require 'swagger_client/models/inline_response_201'
require 'swagger_client/models/inline_response_201_lines'
require 'swagger_client/models/inline_response_400'
require 'swagger_client/models/invoice'
require 'swagger_client/models/invoice_lines'
require 'swagger_client/models/issue_refund_payment'
require 'swagger_client/models/limit'
require 'swagger_client/models/payment_details'
require 'swagger_client/models/price'
require 'swagger_client/models/product'
require 'swagger_client/models/product_tax_type'
require 'swagger_client/models/refund'
require 'swagger_client/models/seats_add_body'
require 'swagger_client/models/seats_remove_body'
require 'swagger_client/models/subscription'
require 'swagger_client/models/subscription_id_cancel_body'
require 'swagger_client/models/subscription_id_extend_body'
require 'swagger_client/models/subscription_id_plan_body'
require 'swagger_client/models/subscription_id_price_body'
require 'swagger_client/models/subscription_plan'
require 'swagger_client/models/subscription_start_body'
require 'swagger_client/models/subscription_trial_body'
require 'swagger_client/models/voucher_code'

# APIs
require 'swagger_client/api/checkout_api'
require 'swagger_client/api/customers_api'
require 'swagger_client/api/invoices_api'
require 'swagger_client/api/payment_details_api'
require 'swagger_client/api/payments_api'
require 'swagger_client/api/prices_api'
require 'swagger_client/api/products_api'
require 'swagger_client/api/receipt_api'
require 'swagger_client/api/refunds_api'
require 'swagger_client/api/subscriptions_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
